### ISSUE TITLE
Undefined variable: $book

### ISSUE THREAD

**Issue by diegomrv** [danielediazmx/laravel-book-library#1]
Hey! really linking your code here but I'm having trouble when getting into the Books tab:

<img width="1216" alt="Screen Shot 2021-05-14 at 11 53 17 a m" src="https://user-images.githubusercontent.com/30731413/118303456-17678680-b4ab-11eb-8349-fadd465ec9c2.png">

The javascript portion is outside of the $books foreach so $book is not defined.

**Comment by danielediazmx** [comment]
Fixed
